apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-vod-app-pvc
  labels:
    app: nginx-vod-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: 100Gi
  storageClassName: longhorn
